<?php

use function Pest\Laravel\get;

beforeEach(function () {
    // TODO: Change the autogenerated stub
    signIn();

    $this->userSettings = auth()->user()->settings();
});

it('does not show a my portal link for visitors', function () {
    auth()->logout();

    get(route('home'))->assertDontSee('my'.str(config('app.name'))->ucfirst());
});

it('is not showing use terms for visitor', function () {
    auth()->logout();

    get(route('frontend.userSettings.edit'))->assertRedirect();
});

it('shows a my portal link for signed in users', function () {
    get(route('home'))->assertSee('my'.str(config('app.name'))->ucfirst());
});

it('shows use terms before activating my portal dashboard', function () {
    get(route('frontend.userSettings.edit'))->assertOk()
        ->assertSee(trans('myPortal.useTerms.use terms'));
});
