<?php

namespace Tests\Feature\Http\Middleware;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AcceptUseTermsTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->signIn();

        $this->userSettings = auth()->user()->settings();
    }

    /** @test */
    public function it_does_not_show_a_myPortal_link_for_visitors(): void
    {
        auth()->logout();

        $this->get(route('home'))->assertDontSee('my'.str(config('app.name'))->ucfirst());
    }

    /** @test */
    public function it_is_not_showing_use_terms_for_visitor(): void
    {
        auth()->logout();

        $this->get(route('frontend.userSettings.edit'))->assertRedirect();
    }

    /** @test */
    public function it_shows_a_myPortal_link_for_signed_in_users(): void
    {
        $this->get(route('home'))->assertSee('my'.str(config('app.name'))->ucfirst());
    }

    /** @test */
    public function it_shows_use_terms_before_activating_my_portal_dashboard(): void
    {
        $this->get(route('frontend.userSettings.edit'))->assertOk()
            ->assertSee(trans('myPortal.useTerms.use terms'));
    }
}
