<?php

namespace Tests\Feature\Http\Controllers\Frontend;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AcceptUseTermsControllerTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->signIn();

        $this->userSettings = auth()->user()->settings();
    }

    /** @test */
    public function it_shows_an_error_if_checkbox_is_not_checked(): void
    {
        $this->put(route('frontend.acceptUseTerms'), ['accept_use_terms' => ''])
            ->assertSessionHasErrors('accept_use_terms');
    }

    /** @test */
    public function it_show_myPortal_index_page_if_use_terms_are_accepted(): void
    {
        $this->followingRedirects()
            ->put(route('frontend.acceptUseTerms'), ['accept_use_terms' => 'on'])
            ->assertSee('Portal Settings');
    }

    /** @test */
    public function it_updates_user_settings_if_user_accepts_use_terms(): void
    {
        $this->assertDatabaseHas('settings', [
            'name' => auth()->user()->username,
            'data' => json_encode(config('settings.user')), ]);

        $this->put(route('frontend.acceptUseTerms'), ['accept_use_terms' => 'on'])
            ->assertSessionDoesntHaveErrors('accept_use_terms');

        $this->userSettings->refresh();

        $this->assertDatabaseHas('settings', [
            'name' => auth()->user()->username,
            'data' => json_encode($this->userSettings->data), ]);
    }
}
