<?php

namespace Tests\Feature\Http\Controllers\Frontend;

use App\Models\Comment;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UserCommentsControllerTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->signIn();

        $this->userSettings = auth()->user()->settings();
    }

    /** @test */
    public function it_shows_user_comments(): void
    {
        $this->acceptUseTerms();

        [$comment1, $comment2 ] = Comment::factory(2)->create(['owner_id' => auth()->user()->id]);

        $this->get(route('frontend.user.comments'))
            ->assertViewHas(['comments' => auth()->user()->comments()->where('type', 'frontend')->get()])
            ->assertViewIs('frontend.myPortal.comments')
            ->assertSee($comment1->content)
            ->assertSee($comment2->content);
    }

    /*
     * Helper functions
     *
     */
    private function acceptUseTerms()
    {
        $this->put(route('frontend.acceptUseTerms'), ['accept_use_terms' => 'on']);
    }
}
