<?php

use App\Models\Comment;

use function Pest\Laravel\get;

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->signIn();

    $this->userSettings = auth()->user()->settings();
});

uses()->group('frontend');
it('shows user comments', function () {
    acceptUseTerms();

    [$comment1, $comment2] = Comment::factory(2)->create(['owner_id' => auth()->user()->id]);

    get(route('frontend.user.comments'))
        ->assertViewHas(['comments' => auth()->user()->comments()->where('type', 'frontend')->get()])
        ->assertViewIs('frontend.myPortal.comments')
        ->assertSee($comment1->content)
        ->assertSee($comment2->content);
});
