<?php

namespace Tests\Unit\Commands;

use App\Models\Asset;
use App\Models\Clip;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Facades\Tests\Setup\ClipFactory;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Facades\Tests\Setup\SeriesFactory;
use Tests\TestCase;

class ReorderPosterImagesTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Storage::fake('player_previews');
        Storage::fake('thumbnails');

        Storage::makeDirectory('player_previews/');
    }

    /** @test */
    public function it_skips_clip_with_no_assets(): void
    {
        $clip = Clip::factory()->create();

        $this->artisan('images:reorder')
            ->expectsOutput('Assets not found for Clip ID '.$clip->id.'! Skipping...');
    }

    /** @test */
    public function it_move_player_previews_to_folders(): void
    {
        UploadedFile::fake()->create('1_preview.img', 100)->storeAs('player_previews', '1_preview.img');
        Storage::assertExists('player_previews');

        $series = SeriesFactory::withClips(4)->withAssets(4)->create();

        $this->assertNull($series->clips->first()->posterImage);

        $this->artisan('images:reorder')->expectsOutput('Finish clip ID '.$series->clips->first()->id);

        $series->refresh();

        $this->assertNotNull($series->clips->first()->posterImage);

        Storage::disk('thumbnails')->assertExists($series->clips->first()->posterImage);
    }
}
