# .travis.yml
dist: focal

language: php

php:
  - 8.0.2

services:
  - postgresql

addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

env:
  global:
    - PGPORT=5432
    - DB_NAME=testing
    - DB_USER=dbowner
    - DB_PASSWORD=dbpassword


cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - psql --command="CREATE USER ${DB_USER};"
  - psql --command="CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit
