# .travis.yml
dist: focal

language: php

php:
  - 8.0.2

services:
  - postgresql

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5433
    - PGUSER=travis

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - psql -c 'create database testing;' -U travis
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit
