<?php

namespace Tests\Feature\Backend;

use Facades\Tests\Setup\ClipFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ClipCommentsTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function an_authenticated_user_can_view_comments_form(): void
    {
        $clip = ClipFactory::create();

        $this->signIn();

        $this->get(route('frontend.clips.show',$clip))->assertSee('Comments');
    }

    /** @test */
    public function an_authenticated_user_can_post_a_comment_to_a_clip(): void
    {
        $clip = ClipFactory::create();

        $this->signIn();

        $this->followingRedirects()
            ->post(route('clip.comments.store', $clip), ['content'=>'test comment'])
            ->assertSee($clip->comments()->first()->content);
    }

    /** @test */
    public function it_displays_an_error_for_empty_comment(): void
    {
        $clip = ClipFactory::create();

        $this->signIn();

        $this->post(route('clip.comments.store', $clip), ['content'=>''])
            ->assertSessionHasErrors('content');
    }

    /** @test */
    public function it_displays_an_error_for_comment_with_less_than_three_characters(): void
    {
        $clip = ClipFactory::create();

        $this->signIn();

        $this->post(route('clip.comments.store', $clip), ['content'=>'12'])
            ->assertSessionHasErrors('content');
    }
}
