<?php


namespace Tests\Feature\Backend;

use App\Enums\OpencastWorkflowState;
use App\Services\OpencastService;
use Facades\Tests\Setup\ClipFactory;
use Facades\Tests\Setup\SeriesFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Storage;
use Tests\Setup\WorksWithOpencastClient;
use Tests\TestCase;

class DashboardTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;
    use WorksWithOpencastClient;

    private string $role;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->role = 'moderator';
    }

    /** @test */
    public function it_should_not_be_accessed_by_a_visitor(): void
    {
        $this->get(route('dashboard'))->assertRedirect('login');
    }

    /** @test */
    public function it_should_not_be_accessed_by_an_authenticated_user(): void
    {
        $this->signIn();

        $this->get(route('dashboard'))->assertStatus(403);
    }

    /** @test */
    public function it_should_be_accessed_by_an_moderator_user(): void
    {
        $this->signInRole($this->role);

        $this->get('admin/dashboard')
            ->assertStatus(200)
            ->assertViewIs('backend.dashboard.index');
    }

    /** @test */
    public function it_should_display_an_add_series_button(): void
    {
        $this->signInRole($this->role);

        $this->get(route('dashboard'))->assertSee('New series');
    }

    /** @test */
    public function it_should_display_an_add_clip_button(): void
    {
        $this->signInRole($this->role);

        $this->get(route('dashboard'))->assertSee('New clip');
    }

    /** @test */
    public function it_should_display_info_if_no_series_exist(): void
    {
        $this->signInRole($this->role);

        $this->get(route('dashboard'))->assertSee('No series found');
    }

    /** @test */
    public function it_should_display_info_if_no_clip_exist(): void
    {
        $this->signInRole($this->role);

        $this->get(route('dashboard'))->assertSee('No clips found');
    }

    /** @test */
    public function it_display_user_series(): void
    {
        $user = $this->signInRole($this->role);

        SeriesFactory::create();

        $this->get(route('dashboard'))->assertSee('No series found');

        $userSeries = SeriesFactory::ownedBy($user)->create();

        $this->get(route('dashboard'))->assertSee($userSeries->title);
    }

    /** @test */
    public function it_display_user_clips(): void
    {
        $user = $this->signInRole($this->role);

        ClipFactory::create();

        $this->get(route('dashboard'))->assertSee('No clips found');

        $userClip = ClipFactory::ownedBy($user)->create();

        $this->get(route('dashboard'))->assertSee($userClip->title);
    }

    /** @test */
    public function it_should_list_all_files_in_drop_zone(): void
    {
        $this->signInRole($this->role);

        Storage::fake('video_dropzone');

        Storage::disk('video_dropzone')->put('test.pdf', 'some non-pdf content');

        $this->get(route('dashboard'))->assertSee('test.pdf');
    }

    /** @test */
    public function it_show_sidebar_menu_items_for_admins()
    {
        $this->signInRole('admin');

        $this->get(route('dashboard'))->assertSee('Opencast')
            ->assertSee('Users');
    }

    /** @test */
    public function it_show_sidebar_menu_items_for_moderators()
    {
        $this->withoutExceptionHandling();
        $this->signInRole($this->role);

        $this->get(route('dashboard'))
            ->assertSee('Series')
            ->assertSee('Clips')
            ->assertSee('Activities')
            ->assertDontSee('Opencast')
            ->assertDontSee('Users');
    }

    /** @test */
    public function it_should_display_opencast_running_workflows_for_admins_if_any(): void
    {
        $series = SeriesFactory::withOpencastID()->create();

        app(OpencastService::class);
        $mockHandler = $this->swapOpencastClient();
        $mockHandler->append($this->mockEventResponse($series, OpencastWorkflowState::RUNNING, 2));
        $this->signInRole('admin');

        $this->get(route('dashboard'))->assertSee('Opencast running workflows');
    }

    /** @test */
    public function it_should_not_display_opencast_running_workflows_for_moderators(): void
    {
        $series = SeriesFactory::withOpencastID()->create();

        app(OpencastService::class);
        $mockHandler = $this->swapOpencastClient();
        $mockHandler->append($this->mockEventResponse($series, OpencastWorkflowState::RUNNING, 2));
        $this->signInRole($this->role);

        $this->get(route('dashboard'))->assertDontSee('Opencast running workflows');
    }

    /** @test */
    public function it_should_not_display_opencast_running_workflows_if_opencast_server_is_not_available(): void
    {
        app(OpencastService::class);
        $mockHandler = $this->swapOpencastClient();
        $mockHandler->append($this->mockServerNotAvailable());
        $this->signInRole('admin');

        $this->get(route('dashboard'))->assertDontSee('Opencast running workflows');
    }
}
