<?php

namespace Tests\Feature\Backend;

use App\Models\Setting;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ManageOpencastSettingsTest extends TestCase
{
    use RefreshDatabase;

    public Setting $setting;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->signInRole('superadmin');

        $this->setting = Setting::create([
            'name' => 'opencast',
            'data' => [
                'url'      => 'localhost:8080',
                'username' => 'admin',
                'password' => 'opencast',
            ],
        ]);
    }

    /** @test */
    public function it_denies_opencast_settings_page_in_roles_other_than_superadmin(): void
    {
        auth()->logout();

        $this->signInRole('moderator');

        $this->get(route('settings.opencast.show'))->assertForbidden();

        auth()->logout();

        $this->signInRole('assistant');

        $this->get(route('settings.opencast.show'))->assertForbidden();

        auth()->logout();

        $this->signInRole('admin');

        $this->get(route('settings.opencast.show'))->assertForbidden();
    }

    /** @test */
    public function it_shows_opencast_settings_page(): void
    {
        $this->get(route('settings.opencast.show'))
            ->assertOk()
            ->assertViewIs('backend.settings.opencast')
            ->assertSee('localhost:8080')
            ->assertSee('admin')
            ->assertSee('Admin password');
    }

    /** @test */
    public function it_requires_an_opencast_admin_url_for_opencast_settings_page(): void
    {
        $attributes = [
            'username' => 'admin',
            'password' => '1234',
        ];

        $this->put(route('settings.opencast.update', $this->setting), $attributes)
            ->assertSessionHasErrors('url');
    }

    /** @test */
    public function it_requires_an_opencast_admin_username_for_opencast_settings_page(): void
    {
        $attributes = [
            'url'      => 'test.com',
            'password' => '1234',
        ];

        $this->put(route('settings.opencast.update', $this->setting), $attributes)
            ->assertSessionHasErrors('username');
    }

    /** @test */
    public function it_requires_an_opencast_admin_password_for_opencast_settings_page(): void
    {
        $attributes = [
            'url'      => 'test.com',
            'username' => 'admin',
        ];

        $this->put(route('settings.opencast.update', $this->setting), $attributes)
            ->assertSessionHasErrors('password');
    }

    /** @test */
    public function it_denies_updating_opencast_settings_in_roles_other_than_superadmin(): void
    {
        auth()->logout();

        $attributes = [
            'url'                   => 'test.com',
            'username'              => 'test',
            'password'              => 1234,
            'archive_path'          => '/archive/mh_default',
            'default_workflow_id'   => 'fast-test',
            'upload_workflow_id'    => 'fast-test',
            'theme_id_top_right'    => '500',
            'theme_id_top_left'     => '501',
            'theme_id_bottom_left'  => '502',
            'theme_id_bottom_right' => '503',
        ];

        $this->signInRole('moderator');

        $this->put(route('settings.opencast.update', $this->setting), $attributes)->assertForbidden();

        auth()->logout();

        $this->signInRole('assistant');

        $this->put(route('settings.opencast.update', $this->setting), $attributes)->assertForbidden();

        auth()->logout();

        $this->signInRole('admin');

        $this->put(route('settings.opencast.update', $this->setting), $attributes)->assertForbidden();

        $this->assertEquals('localhost:8080', Setting::opencast()->data['url']);
    }

    /** @test */
    public function it_updates_opencast_settings_page(): void
    {
        $attributes = [
            'url'                   => 'http://test.com',
            'username'              => 'test',
            'password'              => 1234,
            'archive_path'          => '/archive/mh_default',
            'default_workflow_id'   => 'fast-test',
            'upload_workflow_id'    => 'fast-test',
            'theme_id_top_right'    => '500',
            'theme_id_top_left'     => '501',
            'theme_id_bottom_left'  => '502',
            'theme_id_bottom_right' => '503',
        ];

        $this->put(route('settings.opencast.update', $this->setting), $attributes);

        $this->setting->refresh();

        $this->assertEquals($attributes['url'], $this->setting->opencast()->data['url']);
    }
}
