<?php

namespace Tests\Feature\Backend;

use App\Models\Setting;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ManagePortalSettingsTest extends TestCase
{
    use RefreshDatabase;

    public Setting $setting;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->signInRole('superadmin');

        $this->setting = Setting::portal();
    }

    /** @test */
    public function it_has_portal_settings_page(): void
    {
        $this->get(route('settings.portal.show'))
            ->assertOk()
            ->assertSee('Maintenance mode');
    }

    /** @test */
    public function it_can_set_portal_to_maintenance_mode_via_portal_settings(): void
    {
        $attributes = [
            'maintenance_mode' => "on",
        ];

        $this->put(route('settings.portal.update', $this->setting), $attributes)
            ->assertSessionDoesntHaveErrors('maintenance_mode');

        auth()->logout();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
