<?php

namespace Tests;

use App\Models\Acl;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Acl::create([
            'name'       => 'intern',
            'description' => 'Material is accessed via portal log in',
        ]);

        Acl::create([
            'name'       => 'lms',
            'description' => 'Material is accessed via LMS (moodle, Ilias, etc.) log in',
        ]);

        Acl::create([
            'name'       => 'password',
            'description' => 'Material is accessed via a password (moodle, Ilias, etc.)',
        ]);
    }

    /**
     * @param null $user
     * @return Collection|Model|mixed
     */
    protected function signIn($user = null): mixed
    {
        $user = $user ?: User::factory()->create();

        $this->actingAs($user);

        return $user;
    }

    protected function signInAdmin($user = null)
    {
        $user = $user ?: User::factory()->create();

        $user->assignRole('admin');

        $this->actingAs($user);

        return $user;
    }
}
