<?php

namespace Tests\Feature\Http\Controllers\Backend;

use App\Models\Setting;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ManagePortalSettingsTest extends TestCase
{
    use RefreshDatabase;

    public Setting $setting;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->signInRole('superadmin');

        $this->setting = Setting::portal();
    }

    /** @test */
    public function it_has_portal_settings_page(): void
    {
        $this->get(route('settings.portal.show'))
            ->assertOk()
            ->assertSee('Maintenance mode');
    }

    /** @test */
    public function it_can_set_portal_to_maintenance_mode_via_portal_settings(): void
    {
        $attributes = [
            'maintenance_mode' => 'on',
        ];

        $this->put(route('settings.portal.update', $this->setting), $attributes)
            ->assertSessionDoesntHaveErrors('maintenance_mode');

        auth()->logout();
    }

    /** @test */
    public function it_requires_a_feeds_default_owner_name_field(): void
    {
        $attributes = [];

        $this->put(route('settings.portal.update', $this->setting), $attributes)
            ->assertSessionHasErrors('feeds_default_owner_name');
    }

    /** @test */
    public function a_feeds_default_owner_name_field_must_be_a_string(): void
    {
        $attributes = [
            'feeds_default_owner_name' => true,
        ];

        $this->put(route('settings.portal.update', $this->setting), $attributes)
            ->assertSessionHasErrors('feeds_default_owner_name');

        $attributes = [
            'feeds_default_owner_name' => 'test',
        ];

        $this->put(route('settings.portal.update', $this->setting), $attributes)
            ->assertSessionDoesntHaveErrors('feeds_default_owner_name');
    }

    /** @test */
    public function it_requires_a_feeds_default_owner_email_field(): void
    {
        $attributes = [];

        $this->put(route('settings.portal.update', $this->setting), $attributes)
            ->assertSessionHasErrors('feeds_default_owner_email');
    }

    /** @test */
    public function a_feeds_default_owner_email_field_must_be_an_email(): void
    {
        $attributes = [
            'feeds_default_owner_email' => 'test',
        ];

        $this->put(route('settings.portal.update', $this->setting), $attributes)
            ->assertSessionHasErrors('feeds_default_owner_email');

        $attributes = [
            'feeds_default_owner_email' => 'test@test.com',
        ];

        $this->put(route('settings.portal.update', $this->setting), $attributes)
            ->assertSessionDoesntHaveErrors('feeds_default_owner_email');
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
