<?php

namespace Tests\Feature\Http\Controllers\Backend;

use App\Http\Livewire\UserDataTable;
use App\Mail\EmailUserPassword;
use App\Models\Role;
use App\Models\User;
use Facades\Tests\Setup\ClipFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Notification;
use Livewire\Livewire;
use Tests\TestCase;

class ManageUsersTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->signInRole('admin');
    }

    /** @test */
    public function a_moderator_is_not_allowed_to_view_users_index_page(): void
    {
        auth()->logout();

        $this->get(route('users.index'))->assertRedirect(route('login'));

        $this->signInRole('moderator');

        $this->get(route('users.index'))->assertForbidden();
    }

    /** @test */
    public function it_renders_a_datatable_for_users_with_admin_role(): void
    {
        $this->signInRole('admin');

        $this->get(route('users.index'))->assertOk();
    }

    /** @test */
    public function it_renders_a_datatable_for_users_with_superadmin_role(): void
    {
        $this->signInRole('superadmin');

        $this->get(route('users.index'))->assertOk();
    }

    /** @test */
    public function it_contains_user_data_table_livewire_component_on_index_page(): void
    {
        $this->signInRole('admin');

        $this->get(route('users.index'))->assertSeeLivewire('user-data-table');
    }

    /** @test */
    public function it_has_an_admin_checkbox_in_index_users_data_table_that_filters_admins(): void
    {
        $moderator = $this->signInRole('moderator');
        $admin = $this->signInRole('admin');
        $superadmin = $this->signInRole('superadmin');

        Livewire::test(UserDataTable::class)
            ->assertSee($admin->username)
            ->assertSee($moderator->username)
            ->set('admin', true)
            ->assertSee($admin->username)
            ->assertSee($superadmin->username)
            ->assertDontSee($moderator->username);
    }

    /** @test */
    public function it_can_search_for_user_name_in_index_users_data_table(): void
    {
        [$bob, $alice] = User::factory(2)->create();

        Livewire::test(UserDataTable::class)
            ->set('search', $bob->first_name)
            ->assertSee($bob->username)
            ->assertDontSee($alice->username);
    }

    /** @test */
    public function it_can_search_for_user_email_in_index_users_data_table(): void
    {
        [$bob, $alice] = User::factory(2)->create();

        Livewire::test(UserDataTable::class)
            ->set('search', $bob->email)
            ->assertSee($bob->username)
            ->assertDontSee($alice->username);
    }

    /** @test */
    public function it_can_sorts_by_user_name_ascending_in_index_users_data_table(): void
    {
        $bob = User::factory()->create([
            'first_name' => 'Bob',
            'last_name' => 'Tester',
            'username' => 'bob01',
        ]);
        $alice = User::factory()->create([
            'first_name' => 'Alice',
            'last_name' => 'Tester',
            'username' => 'alice01',
        ]);
        $gregor = User::factory()->create([
            'first_name' => 'Gregor',
            'last_name' => 'Tester',
            'username' => 'gregor01',
        ]);

        Livewire::test(UserDataTable::class)
            ->call('sortBy', 'username')
            ->assertSeeInOrder([$alice->username, $bob->username, $gregor->username]);
    }

    /** @test */
    public function it_can_sorts_by_user_name_descending_in_index_users_data_table(): void
    {
        $bob = User::factory()->create([
            'first_name' => 'Bob',
            'last_name' => 'Tester',
            'username' => 'bob01',
        ]);
        $alice = User::factory()->create([
            'first_name' => 'Alice',
            'last_name' => 'Tester',
            'username' => 'alice01',
        ]);
        $gregor = User::factory()->create([
            'first_name' => 'Gregor',
            'last_name' => 'Tester',
            'username' => 'gregor01',
        ]);

        Livewire::test(UserDataTable::class)
            ->call('sortBy', 'username')
            ->call('sortBy', 'username')
            ->assertSeeInOrder([$gregor->username, $bob->username, $alice->username]);
    }

    /** @test */
    public function it_can_sorts_by_user_email_ascending_in_index_users_data_table(): void
    {
        $bob = User::factory()->create(['email' => 'bob@example.org']);
        $alice = User::factory()->create(['email' => 'alice@example.org']);
        $gregor = User::factory()->create(['email' => 'gregor@example.org']);

        Livewire::test(UserDataTable::class)
            ->call('sortBy', 'email')
            ->assertSeeInOrder([$alice->username, $bob->username, $gregor->username]);
    }

    /** @test */
    public function it_can_sorts_by_user_email_descending_in_index_users_data_table(): void
    {
        $bob = User::factory()->create(['email' => 'bob@example.org']);
        $alice = User::factory()->create(['email' => 'alice@example.org']);
        $gregor = User::factory()->create(['email' => 'gregor@example.org']);

        Livewire::test(UserDataTable::class)
            ->call('sortBy', 'email')
            ->call('sortBy', 'email')
            ->assertSeeInOrder([$gregor->username, $bob->username, $alice->username]);
    }

    /** @test */
    public function a_moderator_is_not_allowed_to_view_user_create_form(): void
    {
        auth()->logout();

        $this->get(route('users.create'))->assertRedirect(route('login'));

        $this->signInRole('moderator');

        $this->get(route('users.create'))->assertForbidden();
    }

    /** @test */
    public function an_admin_user_see_create_a_new_local_user_form(): void
    {
        $this->get(route('users.create'))
            ->assertSee('first_name')
            ->assertSee('last_name')
            ->assertSee('email');
    }

    /** @test */
    public function it_requires_a_first_name_for_creating_a_new_user(): void
    {
        $this->post(route('users.store'), ['first_name' => ''])
            ->assertSessionHasErrors('first_name');

        $this->post(route('users.store'), ['first_name' => '12'])
            ->assertSessionHasErrors('first_name');

        $this->post(route('users.store'), ['first_name' => $this->faker->firstName()])
            ->assertSessionDoesntHaveErrors('first_name');
    }

    /** @test */
    public function it_requires_a_last_name_for_creating_a_new_user(): void
    {
        $this->post(route('users.store'), ['last_name' => ''])
            ->assertSessionHasErrors('last_name');

        $this->post(route('users.store'), ['last_name' => '12'])
            ->assertSessionHasErrors('last_name');

        $this->post(route('users.store'), ['last_name' => 'Doe'])
            ->assertSessionDoesntHaveErrors('last_name');
    }

    /** @test */
    public function it_requires_a_unique_username_for_creating_new_user(): void
    {
        $this->post(route('users.store'), ['username' => ''])
            ->assertSessionHasErrors('username');

        $this->post(route('users.store'), ['username' => auth()->user()->username])
            ->assertSessionHasErrors('username');

        $this->post(route('users.store'), ['username' => 'johndoe21'])
            ->assertSessionDoesntHaveErrors('username');
    }

    /** @test */
    public function it_requires_a_unique_and_valid_email_for_creating_new_user(): void
    {
        $this->post(route('users.store'), ['email' => 'test'])
            ->assertSessionHasErrors('email');

        $this->post(route('users.store'), ['email' => auth()->user()->email])
            ->assertSessionHasErrors('email');

        $this->post(route('users.store'), ['email' => $this->faker->email()])
            ->assertSessionDoesntHaveErrors('email');
    }

    /** @test */
    public function create_user_form_should_remember_old_values_on_validation_error()
    {
        $attributes = [
            'first_name' => $this->faker->firstName(),
            'last_name' => $this->faker->lastName(),
            'username' => $this->faker->userName(),
            'email' => auth()->user()->email,
        ];

        $this->post(route('users.store'), $attributes);

        $this->followingRedirects();

        $this->get(route('users.create'))->assertSee($attributes);
    }

    /** @test */
    public function a_moderator_is_not_allowed_to_create_a_user(): void
    {
        auth()->logout();

        $this->post(route('users.store'), [])->assertRedirect(route('login'));

        $this->signInRole('moderator');

        $this->get(route('users.store'), [])->assertForbidden();
    }

    /** @test */
    public function an_admin_can_create_a_new_user(): void
    {
        $attributes = [
            'first_name' => 'John',
            'last_name' => 'Doe',
            'username' => 'johndoe21',
            'email' => 'john@doe.com',
        ];

        $this->post(route('users.store'), $attributes)->assertStatus(302);

        $this->assertDatabaseHas('users', ['username' => $attributes['username']]);
    }

    /** @test */
    public function after_creation_user_will_be_notified_via_email(): void
    {
        Notification::fake();

        $attributes = [
            'first_name' => 'John',
            'last_name' => 'Doe',
            'username' => 'johndoe21',
            'email' => 'john@doe.com',
        ];

        $this->post(route('users.store'), $attributes);

        Notification::assertNotSentTo([User::find(2)], EmailUserPassword::class);
    }

    /** @test */
    public function a_moderator_is_not_allowed_to_view_user_edit_form(): void
    {
        $user = User::factory()->create();

        auth()->logout();

        $this->get(route('users.edit', $user))->assertRedirect(route('login'));

        $this->signInRole('moderator');

        $this->get(route('users.edit', $user))->assertForbidden();
    }

    /** @test */
    public function admin_user_can_view_edit_user_form(): void
    {
        $user = User::factory()->create();

        $this->get(route('users.edit', $user))
            ->assertOk()
            ->assertSee('first_name')
            ->assertSee('last_name')
            ->assertSee('email')
            ->assertSee('role_id');
    }

    /** @test */
    public function a_moderator_is_not_allowed_to_update_user_information(): void
    {
        $user = User::factory()->create();

        auth()->logout();

        $this->patch(route('users.update', $user), [])->assertRedirect(route('login'));

        $this->signInRole('moderator');

        $this->patch(route('users.update', $user), [])->assertForbidden();
    }

    /** @test */
    public function admin_user_can_update_user_information(): void
    {
        $user = User::factory()->create();

        $this->patch(route('users.update', $user), [
            'first_name' => 'John',
            'last_name' => 'Doe',
            'email' => $user->email,
        ]);

        $user->refresh();

        $this->assertDatabaseHas('users', [
            'first_name' => 'John',
            'last_name' => 'Doe',
            'email' => $user->email,
        ]);
    }

    /** @test */
    public function a_moderator_is_not_allowed_to_delete_a_user(): void
    {
        $user = User::factory()->create();

        auth()->logout();

        $this->delete(route('users.destroy', $user))->assertRedirect(route('login'));

        $this->signInRole('moderator');

        $this->delete(route('users.destroy', $user))->assertForbidden();
    }

    /** @test */
    public function an_admin_user_can_delete_a_user(): void
    {
        $user = User::factory()->create();

        $this->delete(route('users.destroy', $user));

        $this->assertDatabaseMissing('users', ['id' => $user->id]);
    }

    /** @test */
    public function an_admin_can_assign_a_role_to_a_user(): void
    {
        $user = User::factory()->create();

        $this->signInRole('admin');
        $this->patch((route('users.update', $user)), [
            'role_id' => Role::where('name', 'moderator')->first()->id,
        ]);

        $this->assertTrue($user->isModerator());
    }

    /** @test */
    public function it_updates_clip_supervisor_id_if_a_portal_admin_creats_a_clip(): void
    {
        $clip = ClipFactory::ownedBy($adminA = $this->signInRole('admin'))->create();

        $this->assertNotNull($clip->supervisor_id);
    }

    /** @test */
    public function it_updates_clip_supervisor_id_if_a_portal_admin_updates_a_clip(): void
    {
        $clip = ClipFactory::ownedBy($this->signInRole('moderator'))->create();

        $this->assertNull($clip->supervisor_id);

        auth()->logout();

        $this->signInRole('admin');

        $this->patch(route('clips.edit', $clip), [
            'episode' => '1',
            'title' => 'changed',
            'description' => 'changed',
            'recording_date' => now(),
            'organization_id' => '1',
            'language_id' => '1',
            'context_id' => '1',
            'format_id' => '1',
            'type_id' => '1',
            'semester_id' => '1',
        ]);

        $clip->refresh();

        $this->assertNotNull($clip->supervisor_id);
    }
}
