<?php

return [
    'portal' => [
        'maintenance_mode' => false,
        'allow_user_registration' => false,
        'show_dropbox_files_in_dashboard' => true,
        'protected_files_string' => '_Kein',
        'feeds_default_owner_name' => 'Tides',
        'feeds_default_owner_email' => 'itunes@tides.com',
        'default_image_id' => env('DEFAULT_IMAGE_ID', 1),
        'support_email_address' => env('SUPPORT_MAIL_ADDRESS', 'support@tides.com'),
        'admin_main_address' => env('ADMIN_MAIL_ADDRESS', 'admin@tides.org'),
        'player_show_article_link_in_player' => false,
        'player_article_link_url' => 1,
        'player_article_link_text' => '',
        'player_enable_adaptive_streaming' => true,
        'clip_generic_poster_image_name' => 'generic_clip_poster_image.png',
        'a_new_key' => 'default value',
    ],
    'user' => [
        'accept_use_terms' => false,
        'language' => 'de',
        'show_subscriptions_to_home_page' => false,
    ],
    'opencast' => [
        'url' => 'localhost:8080',
        'username' => 'admin',
        'password' => 'opencast',
        'archive_path' => 'archive/mh_default_org',
        'default_workflow' => 'fast',
        'upload_workflow_id' => 'fast',
        'theme_id_top_right' => '500',
        'theme_id_top_left' => '501',
        'theme_id_bottom_left' => '502',
        'theme_id_bottom_right' => '503',
        'assistants_group_name' => 'ROLE_GROUP_TIDES_ASSISTANTS',
    ],
    'streaming' => [
        'wowza_engine_url' => 'localhost:1935',
        'wowza_api_url' => 'localhost:8087',
        'wowza_username' => 'digest_user',
        'wowza_password' => 'digest_password',
        'wowza_content_path' => '/content/videoportal',
        'wowza_secure_token' => 'awsTides12tvv10',
        'wowza_token_prefix' => 'tides',
        'cdn_server_url' => env('CDN_SERVER_URL', 'http://localhost/'),
        'cdn_server_secret' => env('CDN_SERVER_SECRET', 'dsnJ23fjeq!'),
    ],
    'openSearch' => [
        'url' => 'localhost',
        'port' => 9200,
        'username' => 'admin',
        'password' => 'admin',
        'prefix' => 'tides_',
    ],
    'envoy' => [
        'deploy_server' => env('DEPLOY_SERVER', 'localhost'),
        'deploy_repo' => env('DEPLOY_REPO', 'git@github.com/mmz/tides'),
        'deploy_branch' => env('DEPLOY_BRANCH', 'main'),
    ],
];
