<?php

use App\Enums\Role;
use App\Models\User;
use App\Notifications\NewOpencastUserAccountCreated;
use App\Services\OpencastService;
use Tests\Setup\WorksWithOpencastClient;

use function Pest\Laravel\patch;

uses(WorksWithOpencastClient::class);
uses()->group('backend');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    Notification::fake();
    $this->mockHandler = $this->swapOpencastClient();

    $this->opencastService = app(OpencastService::class);
});

it('notifies user to opencast account creation if role changes', function () {
    signInRole(Role::ADMIN);
    $this->mockHandler->append($this->mockCreateAdminUserResponse());

    patch((route('users.update', $user = User::factory()->create())), [
        'roles' => [0 => Role::ASSISTANT()],
    ])->assertRedirect();

    Notification::assertSentTo([$user], NewOpencastUserAccountCreated::class);
});
