<?php

namespace Tests\Feature\Frontend;

use App\Models\Clip;
use Facades\Tests\Setup\ClipFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AccessTest extends TestCase
{
    use RefreshDatabase;

    private Clip $clip;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->clip =  ClipFactory::withAssets(2)->create(['password'=>'1234qwER']);
    }

    /** @test */
    public function a_clip_can_be_only_accessable_for_logged_in_users(): void
    {
        $this->clip->addAcls(collect(['1']));

        $this->get($this->clip->path())->assertDontSee('plyr-player');

        $this->signIn();

        $this->get($this->clip->path())->assertSee('plyr-player');
    }

    /** @test */
    public function a_clip_can_be_only_accessable_for_lms_users(): void
    {
        $this->clip->addAcls(collect(['2']));

        $this->get($this->clip->path())->assertDontSee('plyr-player');

        $time = dechex(time());

        $token = md5('clip' . '1' . $this->clip->password . '0.0.0.0' . $time . 'studon');

        $link = '/protector/link/clip/1/'.$token.'/'.$time.'/studon';

        $this->get($link)->assertStatus(403);

        $token = md5('clip' . '1' . $this->clip->password . '127.0.0.1' . $time . 'studon');

        $link = '/protector/link/clip/1/'.$token.'/'.$time.'/studon';

        $this->get($link)->assertStatus(302);

        $this->get($this->clip->path())->assertSee('plyr-player');
    }

    /** @test */
    public function an_lms_clip_is_accessable_for_clip_owner(): void
    {
        $this->clip->addAcls(collect(['2']));

        $this->get($this->clip->path())->assertDontSee('plyr-player');

        $this->actingAs($this->clip->owner);

        $this->get($this->clip->path())->assertSee('plyr-player');
    }
}
