<?php

namespace Tests\Feature\Frontend;

use App\Models\Clip;
use Facades\Tests\Setup\ClipFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AccessTest extends TestCase
{
    use RefreshDatabase;

    private Clip $clip;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->clip =  ClipFactory::withAssets(2)->create();
    }

    /** @test */
    public function a_clip_can_be_only_accessable_for_logged_in_users(): void
    {
        $this->clip->addAcls(collect(['1']));

        $this->get($this->clip->path())->assertDontSee('plyr-player');

        $this->signIn();

        $this->get($this->clip->path())->assertSee('plyr-player');
    }

    /** @test */
    public function a_clip_can_be_only_accessable_for_lms_users(): void
    {
        $this->withoutExceptionHandling();
        $this->clip->addAcls(collect(['2']));

        $this->get($this->clip->path())->assertDontSee('plyr-player');

        $this->get('protector/link/clip/1/459917e3a2c24f4cbcabe7e5e10c4c6f/60d31cbc/studon/')
                ->assertStatus(200);

        ///protector/link/clip/31887/459917e3a2c24f4cbcabe7e5e10c4c6f/60d31cbc/studon/
//
//        $this->signIn();
//
//
//        $this->get($this->clip->path())->assertSee('plyr-player');
    }
}
