<?php


namespace Tests\Feature\Frontend;

use App\Models\Clip;
use Facades\Tests\Setup\ClipFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ClipTest extends TestCase
{

    use RefreshDatabase;

    private Clip $clip;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->clip = ClipFactory::create();
    }

    /** @test */
    public function a_visitor_cannot_manage_clips(): void
    {
        $this->post(route('clips.store'), [])->assertRedirect('login');

        $this->get(route('clips.create'))->assertRedirect('login');

        $this->patch($this->clip->adminPath(), [])->assertRedirect('login');

        $this->delete($this->clip->adminPath())->assertRedirect('login');
    }

    /** @test */
    public function a_visitor_can_view_a_clip(): void
    {
        $this->get($this->clip->path())->assertSee($this->clip->title);
    }

    /** @test */
    public function an_authorized_user_cannot_view_edit_button_for_not_owned_clip(): void
    {
        $this->signIn();

        $this->get($this->clip->path())->assertDontSee('Back to edit page');
    }

    /** @test */
    public function a_visitor_cannot_see_clip_comments(): void
    {
        $this->get(route('frontend.clips.show',$this->clip))->assertDontSee('Comments');
    }
}
