<?php

use App\Models\Clip;
use Facades\Tests\Setup\SeriesFactory;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

uses(\Illuminate\Foundation\Testing\RefreshDatabase::class);

beforeEach(function () {
    // TODO: Change the autogenerated stub
    Storage::fake('player_previews');
    Storage::fake('thumbnails');

    Storage::makeDirectory('player_previews/');
});

it('skips clip with no assets', function () {
    $clip = Clip::factory()->create();

    $this->artisan('clip:posterImage')->expectsOutput("Assets not found for Clip ID {$clip->id}! Skipping...");
});

it('skips folder creation if clip has no assets', function () {
    Clip::factory()->create();
    $this->artisan('clip:posterImage');

    expect(Storage::disk('thumbnails')->directories())->toBeEmpty();
});

it('updated clip poster path', function () {
    UploadedFile::fake()->create('1_preview.jpg', 100)->storeAs('player_previews', '1_preview.jpg');
    Storage::assertExists('player_previews');

    $series = SeriesFactory::withClips(4)->withAssets(4)->create();

    expect($series->clips->first()->posterImage)->toBeNull();

    $this->artisan('clip:posterImage')->expectsOutput("Finish clip ID {$series->clips->first()->id}");

    $series->refresh();

    expect($series->clips->first()->posterImage)->not->toBeNull();
});
