<?php

namespace App\Models;

use App\Events\SeriesDeleted;
use App\Models\Traits\Accessable;
use App\Models\Traits\Documentable;
use App\Models\Traits\Presentable;
use App\Models\Traits\RecordsActivity;
use App\Models\Traits\Slugable;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Support\Arr;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use Psr\Http\Message\ResponseInterface;

class Series extends BaseModel
{
    use Accessable;
    use Documentable;
    use Presentable;
    use RecordsActivity;
    use Slugable;

    protected $dispatchesEvents = ['deleted' => SeriesDeleted::class];

    protected static function boot()
    {
        parent::boot();
        static::creating(function ($series) {
            $semester = Semester::current()->get()->first()->acronym;
            $series->setSlugAttribute($series->title.'-'.$semester);
        });
    }

    /**
     * Series routes should work with slug and with id to ensure backward compatibility
     */
    public function resolveRouteBinding($value, $field = null): ?Model
    {
        $series = $this->where('slug', $value)->first();
        if (is_null($series)) {
            $series = $this->where('id', (int) $value)->firstOrFail();
        }

        return $series;
    }

    /**
     * Route key should be slug instead of id
     */
    public function getRouteKeyName(): string
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    /**
     * Series public url
     */
    public function path(): string
    {
        return "/series/{$this->slug}";
    }

    /**
     * Series admin edit url
     */
    public function adminPath(): string
    {
        return "/admin/series/{$this->slug}";
    }

    /**
     * A series belongs to a user
     */
    public function owner(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Series subscribers
     */
    public function subscribers(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'series_subscriptions')->withTimestamps();
    }

    /**
     * Add a user to series
     */
    public function addMember(User $moderatorUser): User
    {
        $this->members()->attach($moderatorUser);

        return $moderatorUser;
    }

    /**
     * Series members
     */
    public function members(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'series_members')->withTimestamps();
    }

    /**
     * Remove a user from series
     */
    public function removeMember(User $moderatorUser): User
    {
        $this->members()->detach($moderatorUser);

        return $moderatorUser;
    }

    /**
     * A series belongs to an organization unit
     */
    public function organization(): BelongsTo
    {
        return $this->BelongsTo(Organization::class, 'organization_id', 'org_id');
    }

    /**
     * A series belongs to an image
     */
    public function image(): BelongsTo
    {
        return $this->BelongsTo(Image::class);
    }

    /**
     * A series can have many chapters
     */
    public function chapters(): HasMany
    {
        return $this->hasMany(Chapter::class);
    }

    /**
     * Get all the series's comments.
     */
    public function comments(): MorphMany
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    /**
     * Fetch the latest clip from a series based on episode
     */
    public function latestClip(): HasOne
    {
        return $this->hasOne(Clip::class)->latestOfMany('episode');
    }

    /**
     * Add a clip on a series
     */
    public function addClip(array $validated = []): Clip
    {
        $validated = Arr::add($validated, 'owner_id', auth()->user()->id);

        $clip = $this->clips()->create(Arr::except($validated, ['tags', 'acls', 'presenters']));

        $clip->addTags(collect($validated['tags']));

        return $clip;
    }

    /**
     * A series can have many clips
     */
    public function clips(): HasMany
    {
        return $this->hasMany(Clip::class);
    }

    /**
     * Reorder Series clips based on a collection <id, episode>
     *
     * @return $this
     */
    public function reorderClips(Collection $episodes): static
    {
        $episodes->each(function ($value, $key) {
            $clip = Clip::find($key);
            $clip->episode = $value;
            $clip->save();
        });

        return $this;
    }

    /**
     * Updates opencast series id in series table
     */
    public function updateOpencastSeriesId(ResponseInterface $response): void
    {
        if (! empty($response->getHeaders())) {
            $this->opencast_series_id = Str::afterLast($response->getHeaders()['Location'][0], 'api/series/');

            //do not record this activity
            $this->updateQuietly();
        }
    }

    /**
     * Returns a comma seperated acls list for all clips
     *
     * @return mixed
     */
    public function fetchClipsAcls(): string
    {
        /*
         * for visitors fetch only clips that containing a video asset
         */
        $clips = (auth()->user()?->id === $this->owner_id || auth()->user()?->isAdmin())
            ? $this->clips
            : $this->clips->filter(fn ($clip) => $clip->assets->count() && $clip->is_public);

        //iterate every clip and get a unique acl name
        return $clips->map(function ($clip) {
            return $clip->acls->pluck('name');
        })->flatten()->unique()->values()->implode(', ');
    }

    /**
     * Returns a comma seperated language codes for every series clip
     *
     * @return mixed
     */
    public function clipsLanguageCode(): string
    {
        return $this->clips->map(function ($clip) {
            return $clip->language()->first()->code;
        })->flatten()->unique()->implode(', ');
    }

    public function checkClipAcls(Collection $clips)
    {
        foreach ($clips as $clip) {
            return $clip->checkAcls();
        }
    }

    public function lastPublicClip(): BelongsTo
    {
        return $this->belongsTo(Clip::class);
    }

    public function scopeWithLastPublicClip($query)
    {
        return $query->addSelect(['last_public_clip_id' => Clip::select('id')
            ->public()
            ->whereHas('assets')
            ->whereColumn('series_id', 'series.id')
            ->orderByDesc('recording_date')
            ->take(1),
        ])->with('lastPublicClip');
    }

    /**
     *  Scope a query to only include public series
     */
    public function scopeIsPublic($query): mixed
    {
        return $query->where('is_public', 1);
    }

    public function scopeHasClipsWithAssets($query): mixed
    {
        return $query->whereHas('clips', function ($q) {
            $q->public()->whereHas('assets');
        });
    }

    public function scopeCurrentSemester($query): mixed
    {
        return $query->whereHas('clips', function ($q) {
            $q->whereHas('semester', function ($q) {
                $q->current();
            });
        })->orWhere('owner_id', auth()->user()?->id);
    }

    public function scopeHasOpencastSeriesID($query): mixed
    {
        return $query->Where('opencast_series_id', '<>', '');
    }

    public function clipsWithoutChapter(Chapter $chapter = null): mixed
    {
        return $this->clips->filter(function ($clip) use ($chapter) {
            return ($chapter) ? $clip->chapter_id !== $chapter->id : $clip->chapter_id === null;
        });
    }

    public function fetchLivestreamClip(): ?Clip
    {
        return $this->clips()->where('is_livestream', true)->first();
    }

    public function getSeriesACLSUpdated()
    {
        return $this->clips
            ->map(fn ($clip) => $clip->acls->pluck('name'))->flatten()->unique()->values()
            ->implode(', ');
    }

    protected function title(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => html_entity_decode(
                htmlspecialchars_decode(
                    html_entity_decode(html_entity_decode($value, ENT_NOQUOTES, 'UTF-8'))
                )
            )
        );
    }

    protected function description(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => html_entity_decode(
                htmlspecialchars_decode(
                    html_entity_decode(html_entity_decode($value, ENT_NOQUOTES, 'UTF-8'))
                )
            )
        );
    }
}
