<?php

namespace App\Models;

use App\Events\SeriesDeleted;
use App\Models\Traits\Accessable;
use App\Models\Traits\Documentable;
use App\Models\Traits\Presentable;
use App\Models\Traits\RecordsActivity;
use App\Models\Traits\Slugable;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Support\Arr;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use Psr\Http\Message\ResponseInterface;

class Series extends BaseModel
{
    use Accessable;
    use Documentable;
    use Presentable;
    use Slugable;
    use RecordsActivity;

    protected $dispatchesEvents = ['deleted' => SeriesDeleted::class];

    protected function description(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => html_entity_decode(
                htmlspecialchars_decode(
                    html_entity_decode(html_entity_decode($value, ENT_NOQUOTES, 'UTF-8'))
                )
            )
        );
    }

    /**
     * Series routes should work with slug and with id to ensure backward compatibility
     *
     * @param $value
     * @param $field
     * @return Model|null
     */
    public function resolveRouteBinding($value, $field = null): ?Model
    {
        return $this->where('slug', $value)->orWhere('id', (int) $value)->firstOrFail();
    }

    /**
     * Route key should be slug instead of id
     *
     * @return string
     */
    public function getRouteKeyName(): string
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    /**
     * Series public url
     *
     * @return string
     */
    public function path(): string
    {
        return "/series/{$this->slug}";
    }

    /**
     * Series admin edit url
     *
     * @return string
     */
    public function adminPath(): string
    {
        return "/admin/series/{$this->slug}";
    }

    /**
     * A series can have many clips
     *
     * @return HasMany
     */
    public function clips(): HasMany
    {
        return $this->hasMany(Clip::class);
    }

    /**
     * A series belongs to a user
     *
     * @return BelongsTo
     */
    public function owner(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Series members
     *
     * @return BelongsToMany
     */
    public function members(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'series_members')->withTimestamps();
    }

    /**
     * Series subscribers
     *
     * @return BelongsToMany
     */
    public function subscribers(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'series_subscriptions')->withTimestamps();
    }

    /**
     * Add a user to series
     *
     * @param  User  $moderatorUser
     * @return User
     */
    public function addMember(User $moderatorUser): User
    {
        $this->members()->attach($moderatorUser);

        return $moderatorUser;
    }

    /**
     * Remove a user from series
     *
     * @param  User  $moderatorUser
     * @return User
     */
    public function removeMember(User $moderatorUser): User
    {
        $this->members()->detach($moderatorUser);

        return $moderatorUser;
    }

    /**
     * A series has one organization unit
     *
     * @return HasOne
     */
    public function organization(): HasOne
    {
        return $this->hasOne(Organization::class);
    }

    /**
     * A series can have many chapters
     *
     * @return HasMany
     */
    public function chapters(): HasMany
    {
        return $this->hasMany(Chapter::class);
    }

    /**
     * Get all the series's comments.
     */
    public function comments(): MorphMany
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    /**
     * Fetch the latest clip from a series based on episode
     *
     * @return HasOne
     */
    public function latestClip(): HasOne
    {
        return $this->hasOne(Clip::class)->latestOfMany('episode');
    }

    /**
     * Add a clip on a series
     *
     * @param  array  $validated
     * @return Clip
     */
    public function addClip(array $validated = []): Clip
    {
        $validated = Arr::add($validated, 'owner_id', auth()->user()->id);

        $clip = $this->clips()->create(Arr::except($validated, ['tags', 'acls', 'presenters']));

        $clip->addTags(collect($validated['tags']));

        return $clip;
    }

    /**
     * Reorder Series clips based on a collection <id, episode>
     *
     * @param  Collection  $episodes
     * @return $this
     */
    public function reorderClips(Collection $episodes): static
    {
        $episodes->each(function ($value, $key) {
            $clip = Clip::find($key);
            $clip->episode = $value;
            $clip->save();
        });

        return $this;
    }

    /**
     * Updates opencast series id in series table
     *
     * @param  ResponseInterface  $response
     */
    public function updateOpencastSeriesId(ResponseInterface $response): void
    {
        if (! empty($response->getHeaders())) {
            $this->opencast_series_id = Str::afterLast($response->getHeaders()['Location'][0], 'api/series/');

            $this->update();
        }
    }

    /**
     * Returns a comma seperated acls list for all clips
     *
     * @return mixed
     */
    public function fetchClipsAcls(): string
    {
        //iterate every clip and get a unique acl name
        return $this->clips->map(function ($clip) {
            return $clip->acls()->pluck('name');
        })->flatten()->unique()->values()->implode(', ');
    }

    /**
     *  Scope a query to only include public series
     *
     * @param $query
     * @return mixed
     */
    public function scopeIsPublic($query): mixed
    {
        return $query->where('is_public', 1);
    }

    /**
     * @param $query
     * @return mixed
     */
    public function scopeHasClipsWithAssets($query): mixed
    {
        return $query->whereHas('clips', function ($q) {
            $q->public()->whereHas('assets');
        });
    }

    public function scopeCurrentSemester($query): mixed
    {
        return $query->whereHas('clips', function ($q) {
            $q->whereHas('semester', function ($q) {
                $q->current();
            });
        });
    }

    /**
     * @param $query
     * @return mixed
     */
    public function scopeHasOpencastSeriesID($query): mixed
    {
        return $query->Where('opencast_series_id', '<>', '');
    }

    /**
     * @param  Chapter|null  $chapter
     * @return mixed
     */
    public function clipsWithoutChapter(Chapter $chapter = null): mixed
    {
        return $this->clips->filter(function ($clip) use ($chapter) {
            return $clip->chapter_id !== $chapter->id || $clip->chapter_id === null;
        });
    }
}
