<?php

use App\Models\AcademicDegree;
use Illuminate\Database\Eloquent\Relations\HasMany;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->academicDegree = AcademicDegree::factory()->create();
});

it('belongs to many presenters', function () {
    expect($this->academicDegree->presenters())->toBeInstanceOf(HasMany::class);
});
