<?php

namespace Tests\Unit;

use App\Models\AcademicDegree;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AcademicDegreeTest extends TestCase
{
    use RefreshDatabase;

    protected AcademicDegree $academicDegree;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->academicDegree = AcademicDegree::factory()->create();
    }

    /** @test */
    public function it_belongs_to_many_presenters(): void
    {
        $this->assertInstanceOf(HasMany::class, $this->academicDegree->presenters());
    }
}
