<?php

namespace Tests\Unit;

use App\Models\Clip;
use Facades\Tests\Setup\ClipFactory;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class AccessableTraitTest extends TestCase
{
    use RefreshDatabase;

    protected Clip $clip;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->clip = ClipFactory::withAssets(2)->create(['password' => '1234qweR']);
    }

    /** @test */
    public function it_has_an_acl_method_for_model(): void
    {
        $this->assertInstanceOf(MorphToMany::class, $this->clip->acls());
    }

    /** @test */
    public function it_can_add_acls_to_model(): void
    {
        $this->clip->addAcls(collect(['1', '2']));

        $this->assertEquals(2, $this->clip->acls()->count());
    }

    /** @test */
    public function it_can_check_object_acls(): void
    {
        //clip is open
        $this->assertTrue($this->clip->checkAcls());

        //clip is available only for logged-in users
        $this->clip->addAcls(collect(['2']));

        $this->clip->refresh();

        $this->assertFalse($this->clip->checkAcls());

        $this->signIn();

        $this->assertTrue($this->clip->checkAcls());

        auth()->logout();

        //clip is available for admin user
        $this->assertFalse($this->clip->checkAcls());

        $this->signInRole('admin');

        $this->assertTrue(($this->clip->checkAcls()));

        auth()->logout();

        //clip is now only for LMS users available
        $this->clip->addAcls(collect(['4']));

        $this->clip->refresh();

        $this->assertFalse($this->clip->checkAcls());

        //generate session token cookie for test to pass
        $this->get(generateLMSToken($this->clip, dechex(time()), true));

        $this->assertTrue($this->clip->checkAcls());
    }
}
