<?php


namespace Tests\Unit;

use App\Events\AssetDeleted;
use App\Models\Asset;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;

class AssetTest extends TestCase
{

    use RefreshDatabase;

    private Asset $asset;

    protected function setUp(): void

    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->asset = Asset::factory()->create();
    }

    /** @test */
    public function it_has_a_path()
    {
        $this->assertEquals('/admin/assets/'.$this->asset->id, $this->asset->path());
    }

    /** @test */
    public function delete_an_asset_will_fire_an_event()
    {
        Event::fake();

        $this->asset->delete();

        Event::assertDispatched(AssetDeleted::class);
    }

    /** @test */
    public function it_returns_duration_in_hour_format()
    {
        $this->assertEquals(gmdate("H:i:s", $this->asset->duration), $this->asset->durationToHours());

    }
}
