<?php

use App\Models\Channel;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->channel = Channel::factory()->create();
});

it('belongs to a user', function () {
    expect($this->channel->user())->toBeInstanceOf(BelongsTo::class);
});
