<?php

use App\Models\Chapter;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->chapter = Chapter::factory()->create();
});

it('belongs to a series', function () {
    expect($this->chapter->series())->toBeInstanceOf(BelongsTo::class);
});

it('has many clips', function () {
    expect($this->chapter->clips())->toBeInstanceOf(HasMany::class);
});
