<?php

namespace Tests\Unit;

use App\Models\Clip;
use App\Models\Collection;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CollectionTest extends TestCase
{
    use RefreshDatabase;

    protected Collection $collection;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->collection = Collection::factory()->create();
    }

    /** @test */
    public function it_has_many_clips(): void
    {
        $this->assertInstanceOf(BelongsToMany::class, $this->collection->clips());
    }

    /** @test */
    public function it_can_toggle_clips(): void
    {
        Clip::factory(2)->create();

        $this->collection->toggleClips(collect(['1', '2']));

        $this->assertEquals(2, $this->collection->clips()->count());

        $this->collection->toggleClips(collect(['1', '2']));

        $this->assertEquals(0, $this->collection->clips()->count());
    }
}
