<?php

use App\Models\Context;
use Illuminate\Database\Eloquent\Relations\HasMany;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->context = Context::factory()->create();
});

it('has many clips', function () {
    expect($this->context->clips())->toBeInstanceOf(HasMany::class);
});
