<?php

namespace Tests\Unit;

use App\Models\Device;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class DeviceTest extends TestCase
{
    use RefreshDatabase;

    private Device $device;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->device = Device::factory()->create();
    }

    /** @test */
    public function it_belongs_to_a_location(): void
    {
        $this->assertInstanceOf(BelongsTo::class, $this->device->location());
    }

    /** @test */
    public function it_belongs_to_an_organization(): void
    {
        $this->assertInstanceOf(BelongsTo::class, $this->device->organization());
    }
}
