<?php

use App\Models\DeviceLocation;
use Illuminate\Database\Eloquent\Relations\HasMany;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->deviceLocation = DeviceLocation::factory()->create();
});

test('a location can have many devices', function () {
    expect($this->deviceLocation->devices())->toBeInstanceOf(HasMany::class);
});
