<?php

namespace Tests\Unit;

use App\Models\DeviceLocation;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class DeviceLocationsTest extends TestCase
{
    use RefreshDatabase;

    private DeviceLocation $deviceLocation;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->deviceLocation = DeviceLocation::factory()->create();
    }

    /** @test */
    public function a_location_can_have_many_devices(): void
    {
        $this->assertInstanceOf(HasMany::class, $this->deviceLocation->devices());
    }
}
