<?php

use App\Models\Device;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->device = Device::factory()->create();
});

it('belongs to a location', function () {
    expect($this->device->location())->toBeInstanceOf(BelongsTo::class);
});

it('belongs to an organization', function () {
    expect($this->device->organization())->toBeInstanceOf(BelongsTo::class);
});
