<?php

use App\Models\Document;
use Illuminate\Database\Eloquent\Relations\MorphToMany;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->document = Document::factory()->create();
});

it('may have many series', function () {
    expect($this->document->series())->toBeInstanceOf(MorphToMany::class);
});

it('may have many clips', function () {
    expect($this->document->clips())->toBeInstanceOf(MorphToMany::class);
});
