<?php

namespace Tests\Unit;

use App\Models\Document;
use Illuminate\Database\Eloquent\Relations\MorphToMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class DocumentTest extends TestCase
{
    use RefreshDatabase;

    protected Document $document;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->document = Document::factory()->create();
    }

    /** @test */
    public function it_may_have_many_series(): void
    {
        $this->assertInstanceOf(MorphToMany::class, $this->document->series());
    }

    /** @test */
    public function it_may_have_many_clips(): void
    {
        $this->assertInstanceOf(MorphToMany::class, $this->document->clips());
    }
}
