<?php

namespace Tests\Unit;

use App\Models\Format;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class FormatTest extends TestCase
{
    use RefreshDatabase;

    private Format $format;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->format = Format::factory()->create();
    }

    /** @test */
    public function it_has_many_clips(): void
    {
        $this->assertInstanceOf(HasMany::class, $this->format->clips());
    }
}
