<?php

namespace Tests\Unit;

use App\Models\Image;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ImageTest extends TestCase
{
    use RefreshDatabase;

    private Image $image;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->image = Image::factory()->create();
    }

    /** @test */
    public function it_has_many_series(): void
    {
        $this->assertInstanceOf(HasMany::class, $this->image->series());
    }

    /** @test */
    public function it_has_many_clips(): void
    {
        $this->assertInstanceOf(HasMany::class, $this->image->clips());
    }
}
