<?php

use App\Models\Language;
use Illuminate\Database\Eloquent\Relations\HasMany;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->language = Language::factory()->create();
});

it('has many clips', function () {
    expect($this->language->clips())->toBeInstanceOf(HasMany::class);
});
