<?php

use App\Models\Organization;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\HasMany;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->organization = Organization::factory()->create();
});

it('has many clips', function () {
    expect($this->organization->clips())->toBeInstanceOf(HasMany::class);
});

it('has a chairs scope', function () {
    expect($this->organization->chairs())->toBeInstanceOf(Builder::class);
});
