<?php

namespace Tests\Unit;

use App\Models\Organization;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class OrganizationTest extends TestCase
{
    use RefreshDatabase;

    private Organization $organization;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->organization = Organization::factory()->create();
    }

    /** @test */
    public function it_has_many_clips(): void
    {
        $this->assertInstanceOf(HasMany::class, $this->organization->clips());
    }

    /** @test */
    public function it_has_a_chairs_scope(): void
    {
        $this->assertInstanceOf(Builder::class, $this->organization->chairs());
    }
}
