<?php

use App\Models\Clip;
use App\Models\Presenter;
use App\Models\Series;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->clip = Clip::factory()->create();
    $this->series = Series::factory()->create();
    Presenter::factory(2)->create();
});

it('can add presenters to a clip', function () {
    $this->clip->addPresenters(collect(['1', '2']));

    expect($this->clip->presenters()->count())->toEqual(2);
});

it('can add presenters to a series', function () {
    $this->series->addPresenters(collect(['1', '2']));

    expect($this->series->presenters()->count())->toEqual(2);
});
