<?php

namespace Tests\Unit;

use App\Models\Clip;
use App\Models\Presenter;
use App\Models\Series;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PresentableTraitTest extends TestCase
{
    use RefreshDatabase;

    protected Clip $clip;
    protected Series $series;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->clip = Clip::factory()->create();
        $this->series = Series::factory()->create();
    }

    /** @test */
    public function it_can_add_presenters_to_a_clip(): void
    {
        Presenter::factory(2)->create();
        $this->clip->addPresenters(collect(['1', '2']));

        $this->assertEquals(2, $this->clip->presenters()->count());
    }

    /** @test */
    public function it_can_add_presenters_to_a_series(): void
    {
        Presenter::factory(2)->create();
        $this->series->addPresenters(collect(['1', '2']));

        $this->assertEquals(2, $this->series->presenters()->count());
    }
}
