<?php

use App\Models\Type;
use Illuminate\Database\Eloquent\Relations\HasMany;

uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->type = Type::factory()->create();
});

it('has many clips', function () {
    expect($this->type->clips())->toBeInstanceOf(HasMany::class);
});
