<?php

use App\Http\Livewire\SubscribeSection;
use Facades\Tests\Setup\SeriesFactory;
use Livewire\Livewire;

use function Pest\Laravel\assertDatabaseHas;
use function Pest\Laravel\assertDatabaseMissing;
use function Pest\Laravel\get;

uses()->group('backend');

beforeEach(function () {
    // TODO: Change the autogenerated stub
    signIn();

    $this->series = SeriesFactory::withClips(1)->withAssets(3)->create();
});

it('does not contain subscribe section for non logged in users', function () {
    auth()->logout();

    get(route('frontend.series.show', $this->series))->assertDontSeeLivewire('subscribe-section');
});

it('does contain subscribe section for logged in users', function () {
    get(route('frontend.series.show', $this->series))->assertSeeLivewire('subscribe-section');
});

it('can subscribe a user to a series', function () {
    assertDatabaseMissing('series_subscriptions', [
        'user_id' => auth()->user()->id,
        'series_id' => $this->series->id,
    ]);

    Livewire::test(SubscribeSection::class, [
        'series' => $this->series,
    ])->call('subscribe');

    assertDatabaseHas('series_subscriptions', [
        'user_id' => auth()->user()->id,
        'series_id' => $this->series->id,
    ]);
});

it('can unsubscribe a user from a serries', function () {
    auth()->user()->subscriptions()->attach($this->series);

    assertDatabaseHas('series_subscriptions', [
        'user_id' => auth()->user()->id,
        'series_id' => $this->series->id,
    ]);

    Livewire::test(SubscribeSection::class, [
        'series' => $this->series,
    ])->call('unsubscribe');

    assertDatabaseMissing('series_subscriptions', [
        'user_id' => auth()->user()->id,
        'series_id' => $this->series->id,
    ]);
});
