<?php

use App\Enums\Acl;
use App\Http\Livewire\UnlockObject;
use Facades\Tests\Setup\SeriesFactory;
use Livewire\Livewire;

use function Pest\Laravel\get;

beforeEach(function () {
    // TODO: Change the autogenerated stub
    $this->series = SeriesFactory::withClips(2)->withAssets(1)->create(['password' => '1234QWer']);
});

it('load component in series page if has a clip with password acl', function () {
    get(route('frontend.series.show', $this->series))->assertDontSeeLivewire('unlock-object');
    $firstClip = $this->series->clips()->first();

    $firstClip->addAcls(collect([Acl::PASSWORD()]));

    get(route('frontend.series.show', $this->series))->assertSeeLivewire('unlock-object');
});

it('has session errors if unlock password is empty', function () {
    Livewire::test(UnlockObject::class, [
        'model' => $this->series,
    ])->set('password', '')
        ->call('unlock')
        ->assertHasErrors(['password' => 'required']);
});

it('has session errors if unlock password is simple', function () {
    Livewire::test(UnlockObject::class, [
        'model' => $this->series,
    ])->set('password', '1234')
        ->call('unlock')
        ->assertHasErrors(['password']);
});

it('has session errors if unlock password does not match', function () {
    Livewire::test(UnlockObject::class, [
        'model' => $this->series,
    ])->set('password', '1234qwER')
        ->call('unlock')
        ->assertHasErrors(['password']);
});

it('redirects if unlock password does match', function () {
    Livewire::test(UnlockObject::class, [
        'model' => $this->series,
    ])->set('password', '1234QWer')
        ->call('unlock')
        ->assertSessionHasNoErrors()
        ->assertRedirect(route('frontend.series.show', $this->series));
});
