<?php

namespace Tests\Feature\Http\Livewire;

use App\Enums\Acl;
use App\Http\Livewire\UnlockObject;
use App\Models\Series;
use Facades\Tests\Setup\SeriesFactory;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Tests\TestCase;

class UnlockObjectTest extends TestCase
{
    use RefreshDatabase;

    private Series $series;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->series = SeriesFactory::withClips(2)->withAssets(1)->create(['password' => '1234QWer']);
    }

    /** @test */
    public function it_load_component_in_series_page_if_has_a_clip_with_password_acl(): void
    {
        $this->get(route('frontend.series.show', $this->series))->assertDontSeeLivewire('unlock-object');
        $firstClip = $this->series->clips()->first();

        $firstClip->addAcls(collect([Acl::PASSWORD()]));

        $this->get(route('frontend.series.show', $this->series))->assertSeeLivewire('unlock-object');
    }

    /** @test */
    public function it_has_session_errors_if_unlock_password_is_empty(): void
    {
        Livewire::test(UnlockObject::class, [
            'model' => $this->series,
        ])->set('password', '')
            ->call('unlock')
            ->assertHasErrors(['password' => 'required']);
    }

    /** @test */
    public function it_has_session_errors_if_unlock_password_is_simple(): void
    {
        Livewire::test(UnlockObject::class, [
            'model' => $this->series,
        ])->set('password', '1234')
            ->call('unlock')
            ->assertHasErrors(['password']);
    }

    /** @test */
    public function it_has_session_errors_if_unlock_password_does_not_match(): void
    {
        Livewire::test(UnlockObject::class, [
            'model' => $this->series,
        ])->set('password', '1234qwER')
            ->call('unlock')
            ->assertHasErrors(['password']);
    }

    /** @test */
    public function it_redirects_if_unlock_password_does_match(): void
    {
        Livewire::test(UnlockObject::class, [
            'model' => $this->series,
        ])->set('password', '1234QWer')
            ->call('unlock')
            ->assertSessionHasNoErrors()
            ->assertRedirect(route('frontend.series.show', $this->series));
    }
}
