<?php

use App\Services\OpenSearchService;
use Facades\Tests\Setup\ClipFactory;
use Facades\Tests\Setup\SeriesFactory;
use Illuminate\Support\Collection;
use Tests\Setup\WorksWithOpenSearchClient;

uses(WorksWithOpenSearchClient::class);
uses()->group('unit');

beforeEach(function () {
    // TODO: Change the autogenerated stub
});

it('creates a series index if OpenSearch is available', function () {
    $series = SeriesFactory::create();
    $this->startStream($series);
    $this->mockSingleDocument();
    $openSearchService = app(OpenSearchService::class);
    $response = $openSearchService->fetchDocument('tides_series', 'series_1');

    expect($response->get('hits')['hits'][0]['_source']['title'])->toEqual($series->title);
    expect($response)->toBeInstanceOf(Collection::class);
});

it('creates a clip index if OpenSearch is available', function () {
    $clip = ClipFactory::create();
    $this->startStream($clip);
    $this->mockSingleDocument();
    $openSearchService = app(OpenSearchService::class);
    $response = $openSearchService->fetchDocument('tides_clip', 'clip_1');

    expect($response->get('hits')['hits'][0]['_source']['title'])->toEqual($clip->title);
    expect($response)->toBeInstanceOf(Collection::class);
});

afterEach(function () {
    // TODO: Change the autogenerated stub
    $this->closeStream();
});
